### ISSUE TITLE
项目开起来是空的怎么回事

### ISSUE THREAD

**Issue by JLsatisfied** [sanfengliao/vue-juejin#1]
项目开起来是空的怎么回事，只有底部图标存在

**Comment by sanfengliao** [comment]
> 项目开起来是空的怎么回事，只有底部图标存在

加1164406557交流一下

**Comment by xldou-cn** [comment]
是不是rem没有引入的问题？html元素上没有fontSize

**Comment by JLsatisfied** [comment]
@xldou-cn 你可以正常看到吗？有的，设置了0.5px

**Comment by xldou-cn** [comment]
我再源码里面没看到设置的地方，启动起来html元素上没有font-size属性

**Comment by xldou-cn** [comment]
我以为是js自适应的,原来是css媒体查询的
